Name:           ros-kinetic-cob-linear-nav
Version:        0.6.6
Release:        0%{?dist}
Summary:        ROS cob_linear_nav package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://ros.org/wiki/cob_linear_nav
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-actionlib
Requires:       ros-kinetic-cob-srvs
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-move-base-msgs
Requires:       ros-kinetic-nav-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-tf
BuildRequires:  ros-kinetic-actionlib
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cob-srvs
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-move-base-msgs
BuildRequires:  ros-kinetic-nav-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-tf

%description
cob_linear_nav provides a simple navigation instrument driving on a linear path
from current position to goal without any planning or obstacle avoidance
capabilites. Obstacle avoidance should be carried out in other package, e.g.
cob_collision_velocity_filter.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sun Jan 07 2018 Felix Zeltner <fez@ipa.fraunhofer.de> - 0.6.6-0
- Autogenerated by Bloom

* Tue Jul 25 2017 Matthias Gruhler <mig@ipa.fraunhofer.de> - 0.6.5-0
- Autogenerated by Bloom

