%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-cob-navigation-global
Version:        0.6.11
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS cob_navigation_global package

License:        Apache 2.0
URL:            http://ros.org/wiki/cob_navigation_global
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-amcl
Requires:       ros-noetic-cob-default-env-config
Requires:       ros-noetic-cob-linear-nav
Requires:       ros-noetic-cob-navigation-config
Requires:       ros-noetic-cob-scan-unifier
Requires:       ros-noetic-dwa-local-planner
Requires:       ros-noetic-map-server
Requires:       ros-noetic-move-base
Requires:       ros-noetic-rviz
Requires:       ros-noetic-topic-tools
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-cob-default-env-config
BuildRequires:  ros-noetic-cob-supported-robots
BuildRequires:  ros-noetic-roslaunch
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
This package holds config and launch files for running the move_base node on the
Care-O-bot. The move_base node is configured to run over a pre-specified static
map.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Oct 22 2020 Felix Zeltner <fez@ipa.fraunhofer.de> - 0.6.11-1
- Autogenerated by Bloom

