Name:           ros-hydro-cob-navigation-global
Version:        0.5.3
Release:        0%{?dist}
Summary:        ROS cob_navigation_global package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_navigation_global
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-amcl
Requires:       ros-hydro-cob-default-env-config
Requires:       ros-hydro-cob-linear-nav
Requires:       ros-hydro-cob-navigation-config
Requires:       ros-hydro-cob-scan-unifier
Requires:       ros-hydro-map-server
Requires:       ros-hydro-move-base
Requires:       ros-hydro-navigation
Requires:       ros-hydro-rviz
Requires:       ros-hydro-topic-tools
BuildRequires:  ros-hydro-catkin

%description
This package holds config and launch files for running the move_base node on the
Care-O-bot. The move_base node is configured to run over a pre-specified static
map.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Aug 31 2015 Matthias Gruhler <mig@ipa.fraunhofer.de> - 0.5.3-0
- Autogenerated by Bloom

